[tool.poetry]
name = "aoc2022"
version = "0.1.0"
description = ""
authors = ["cauesmelo <cauesmelo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
